Dev/hardknott/grub
ni/meta-nilrt pull request #260
Opened 2021-10-28 13:58 UTC by billpittman

This change allows us to use upstream grub instead of ni/grub.  Also removes some dated TPM code.  Fixes some naming issues and recipe issues that allow grub to build without warnings.

Also this has been tested on my 9032 hardware and the target still behaves wrt the CPLD operations.

2021-10-28 14:28 UTC, amstewart commented on recipes-bsp/grub/grub-nilrt.inc
> +	file://cmd-test-Add-bitwise-AND-document-the-feature.patch \
If any of these .patches are related to each other, we should express an ordering by prepending the file name like `0001_*`. Is that not the case?

2021-10-28 14:28 UTC, amstewart commented on recipes-bsp/grub/grub-efi_git.bbappend
> +PACKAGES_prepend = "${PN}-nilrt "
NIT: Should this line have been a part of the previous commit?

2021-10-28 14:28 UTC, amstewart commented on recipes-bsp/grub/grub/grub-safemode.cfg
>  # NI Linux RT grub boot configuration script
What's with all the changes in this file?

2021-10-28 14:31 UTC, bstreiff commented on recipes-bsp/grub/grub/add-inbit-command-to-io-module.patch
> +From 48de0b2faec205e874099e0afdc14ab70919e702 Mon Sep 17 00:00:00 2001
Do we need this one? The bitwise-and patch describes itself as replacing the functionality of "inbit".

2021-10-28 17:59 UTC, billpittman commented on recipes-bsp/grub/grub-nilrt.inc
> +	file://cmd-test-Add-bitwise-AND-document-the-feature.patch \
They are only related in the sense that they're all NI commits/patches.  They don't share files and they don't depend on one another.  That said I really don't care how they're named, want me to name them 0001-* 0002-* and 0003-* arbitrarily (which lets all admit will turn into alphabetical) ??

2021-10-28 18:00 UTC, billpittman commented on recipes-bsp/grub/grub-efi_git.bbappend
> +PACKAGES_prepend = "${PN}-nilrt "
True enough, but I also removed the measure component, and that moved the "file" into this commit.  Want me to split the two changes so they can go in appropriate commits ?

2021-10-28 18:01 UTC, billpittman commented on recipes-bsp/grub/grub/grub-safemode.cfg
>  # NI Linux RT grub boot configuration script
Removing the measure.mod from grub (the commit Haris added that we've now dropped), caused the measure command to be unknown, so I removed all the references to measure (since they're related to TPM).

2021-10-28 18:03 UTC, billpittman commented on recipes-bsp/grub/grub/add-inbit-command-to-io-module.patch
> +From 48de0b2faec205e874099e0afdc14ab70919e702 Mon Sep 17 00:00:00 2001
Totally agree with you, however looking at the grub-safemode.cfg file, there are still calls to inbit if the cpld_test value is $e5 (not sure what $e5 means, probably the "old version" of the cpld/smbios handling code?!?!?).

2021-10-28 18:04 UTC, chaitu236 commented on recipes-bsp/grub/grub/grub-safemode.cfg
>  # NI Linux RT grub boot configuration script
Why did we add `measure` before and why are we removing it now?

2021-10-28 18:09 UTC, billpittman commented on recipes-bsp/grub/grub/grub-safemode.cfg
>  # NI Linux RT grub boot configuration script
measure was for TPM implementations - my understanding on that is two fold, one the API has changed, so most/some/all of our implementation will need to change, and two we never sold it, and nobody's asking for it, so its not is the mvp.

2021-10-28 21:28 UTC, amstewart commented on recipes-bsp/grub/grub-nilrt.inc
> +	file://cmd-test-Add-bitwise-AND-document-the-feature.patch \
Nope; if they're not related, then I don't see a need to enforce an order.

2021-10-28 21:29 UTC, amstewart commented on recipes-bsp/grub/grub-efi_git.bbappend
> +PACKAGES_prepend = "${PN}-nilrt "
I mean... I would like you to; yes. :)

2021-10-28 21:31 UTC, amstewart requested changes
Looks good; pending testing on a physical system and the minor NIT above.

2021-10-28 21:51 UTC, chaitu236 approved these changes

2021-10-29 14:16 UTC, billpittman commented
Both fixed now.

2021-10-29 17:25 UTC, amstewart approved these changes

2021-11-01 15:18 UTC, amstewart commented
Do you approve, @bstreiff ?

2021-11-01 16:41 UTC, bstreiff approved these changes

2021-11-01 17:51 UTC, merged