Build ja_JP.WINDOWS-31J locale for LabVIEW usage.
ni/meta-nilrt pull request #391
Opened 2022-05-09 16:37 UTC by SparkingSpork

Add glibc patch to build windows-31j locale.

Signed-off-by: Charlie Johnston <charlie.johnston@ni.com>

Azure Work-Item: https://dev.azure.com/ni/DevCentral/_workitems/edit/1908372/

Testing Performed:
Built locally and confirmed the new ja_JP.WINDOWS-31J locale files were built.
Tested installing the locale files to a target and setting them as a locale.

2022-05-09 17:00 UTC, chaitu236 approved these changes

2022-05-09 17:00 UTC, chaitu236 commented on recipes-core/glibc/glibc_2.%.bbappend
> +"
nitpick: Can you save this file on a linux machine so newline is added?

2022-05-09 18:16 UTC, amstewart requested changes

2022-05-09 18:16 UTC, amstewart commented on recipes-core/glibc/glibc/windows-31j_support.patch
> +
Could you add an Upstream Status trailer here, [per the styleguide](https://github.com/ni/nilrt/blob/nilrt/master/hardknott/docs/CONTRIBUTING.md#patch-files)? And also note the rationale for the .patch in the summary.

2022-05-10 17:14 UTC, amstewart approved these changes

2022-05-10 17:14 UTC, amstewart commented on recipes-core/glibc/glibc/windows-31j_support.patch
> +For Japanese locales, glibc only incudes unicode-based locales right now but
s/incudes/includes/

2022-05-12 14:20 UTC, jeminor approved these changes

2022-05-13 17:15 UTC, shruthi-ravi approved these changes

2022-05-13 17:18 UTC, merged