Adding required SystemLink package to run mode file system
ni/meta-nilrt pull request #399
Opened 2022-06-01 21:35 UTC by SparkingSpork

Adding python3-ni-asset-discovery to NI_PROPRIETARY_RUNMODE_PACKAGES.

Signed-off-by: Charlie Johnston <charlie.johnston@ni.com>

AzDO Work Item: https://dev.azure.com/ni/DevCentral/_workitems/edit/1990884/

# Testing
Built locally and deployed BSI to a target. Confirmed the following path existed and that the package was installed:
`/usr/lib/python3.5/site-packages/asset_discovery/`

2022-06-01 21:38 UTC, amstewart requested changes
Changes look fine, but could you expand the commit to explain why we're doing this work.

2022-06-01 22:13 UTC, SparkingSpork commented
> Changes look fine, but could you expand the commit to explain why we're doing this work.

Added more details to the commit.

2022-06-01 22:20 UTC, shruthi-ravi approved these changes

2022-06-02 06:53 UTC, amstewart approved these changes

2022-06-02 06:54 UTC, merged