ni-base-system-image-tests: Perform a three-way diff
ni/meta-nilrt pull request #539
Opened 2023-02-27 22:12 UTC by mike-petersen-ni

As mentioned in a comment on #534, during a discussion with @jpautler we determined that we had some contradictory requirements for this test's output:
 - only list the changes since the latest M.m.p.b version (the previous run), to make test results easier to interpret
 - list all the changes since the latest M.m.p version, to avoid accidentally ignoring changes since the last "release" (which is not *released* per se, but rather the last triplet-version before a version bump)

We assessed whether we wanted to make a custom streak indexer, which could allow each path to be reported as its own test case. This was undesirable due to the probable large amount of noise and difficulty of correlating failures.

# Changes
Two manifests are retrieved from the database. (The query may find the same manifest twice, which is expected on occasion.)
They are referred to as the "basis" and "recent" manifests, with the basis manifest being at least as old as the recent manifest.

The manifests are diffed with set operations and filters, as before. However, each of the three manifests is diffed against the other two (so the diffing work has technically tripled, though the test still completes in seconds):

         current                      23.3.0d11
          ^  ^                          ^  ^
         /    \        e.g.            /    \
        v      v                      v      v
    basis <--> recent        23.0.0f100 <--> 23.3.0d10

Doing this allows all three diffs to be considered and included in the output, to meet the needs of the test.
These diffs are referred to in the code as "net" (basis <-> current), "seen" (basis <-> recent), and "unseen" (recent <-> current).

## Output format
A legend is printed first:

    LEGEND:
    c: X changed relative to Y
    +: X has a path that Y does not
    -: Y has a path that X does not
    *   X=current Y=basis  (new issues since the last run for previous MAJOR.MINOR.PATCH)
     *  X=recent  Y=basis  (issues seen in the last run)
      * X=current Y=recent (new issues since the last run, probably for this MAJOR.MINOR.PATCH)

and as indicated, the first three columns of each line are used to indicate the type of difference for each of the comparisons.
As with the previous test, files without any differences are not printed, though now there must be no differences in any of the three diffs.

The ordering of the differences as they are printed is in order of whether they are affected by certain diffs. First "unseen" differences are shown, since they are new to the run and more likely to be interesting; then "net" differences are shown, since they are the overall differences that we'd care about for release checks; then "seen" differences are shown for completeness.  
The code **does not go to any effort to sort the paths**, but that can be easily fixed.

Here are some snippets of output as an example:

1. ```
    +- /bin/vi: recent mode = lrwxrwxrwx, user = admin, group = administrators
   ++c /bin: current mode = drwxrwxr-x, user = admin, group = administrators; recent mode = drwxr-xr-x, user = admin, group = administrators
   + + /bin/vi.bak: current mode = lrwxrwxrwx, user = admin, group = administrators
   ```
2. ```
   - - /bin/vi.bak: basis mode = lrwxrwxrwx, user = admin, group = administrators; recent mode = lrwxrwxrwx, user = admin, group = administrators
   + + /bin/vi: current mode = lrwxrwxrwx, user = admin, group = administrators
   c c /bin: current mode = drwxr-xr-x, user = admin, group = administrators; basis mode = drwxrwxr-x, user = admin, group = administrators; recent mode = drwxrwxr-x, user = admin, group = administrators
   ```
3. ```
    cc /bin: current mode = drwxrwxr-x, user = admin, group = administrators; basis mode = drwxrwxr-x, user = admin, group = administrators; recent mode = drwxr-xr-x, user = admin, group = administrators
   ++  /bin/vi: current mode = lrwxrwxrwx, user = admin, group = administrators; recent mode = lrwxrwxrwx, user = admin, group = administrators
   --  /bin/vi.bak: basis mode = lrwxrwxrwx, user = admin, group = administrators
   ```

# Testing
 - I have done stuff (sample output above is generated by the test), will clarify here soon

# Merging
This should be cherry-picked into nilrt/master/hardknott, as with #534. I'll rebase upon request.

2023-02-28 21:27 UTC, mike-petersen-ni commented
# Patch draft-v2
 - avoid stripping command output (messes with the hash: in-memory manifest differs from uploaded manifest by a newline)
 - rewrote `Logger`'s `first_log` into `prefix_log`
 - print codename in "finding previous manifest" logging
 - sort paths before diffing
 - move recent hash to second line (not useful for streak indexer)
 - additionally provide simple two-way diff limited to just "unseen" changes
 - add a note to the log to help people know which column of the diff is actually responsible for test failures

2023-03-02 01:17 UTC, jpautler commented on recipes-ni/ni-base-system-image-tests/files/fs_permissions_diff.py
> +            # If there are no results, there may not be a run from the current os version.
Nit, I think you mean "there **must** not be a run from the current os **codename**".

2023-03-02 01:17 UTC, jpautler commented on recipes-ni/ni-base-system-image-tests/files/fs_permissions_diff.py
> +    logger.prefix_logs[0] += f'(basis={basis_hash}, current={current_hash})'
The first line is getting long. To keep the failure mode strings in dashboard reasonable, we only take the first 100 characters of the first line of output. By my estimate, you're probably up around 90 characters not including the two actual hash values. If we think we need to change that limit, we should probably discuss.

2023-03-02 01:17 UTC, jpautler commented on recipes-ni/ni-base-system-image-tests/files/fs_permissions_diff.py
> +    logger.log('###### Unseen two-way diff: current vs recent ######')
Having read the description of this PR, I get what "unseen" means. But for someone else looking at just the ATS results it might be less clear. Could we describe this section as "Differences since last test run: current vs recent"? Does that seem clearer but still reasonably accurate?

2023-03-02 01:17 UTC, jpautler commented on recipes-ni/ni-base-system-image-tests/files/fs_permissions_diff.py
> +    logger.log('###### begin unseen diff ######')
If we change the "unseen" nomenclature, we should change it here and in the matching end comment as well.

2023-03-02 01:17 UTC, jpautler commented on recipes-ni/ni-base-system-image-tests/files/fs_permissions_diff.py
> +        logger.log('INFO: Using previous fs permissions of OS {} {} from {} with _id {}'.format(result['os_version_codename'], result['os_version_full'], result['date'], result['_id']))
Could we replace the output generated from this line with something similar to this:

basis   = 23.0.0.f147 from 1/27/2023 with _id = 432987123
recent  = 23.3.0.d102 from 2/27/2023 with _id = 432987234
current = 23.3.0.d103 from 3/1/2023 with _id = 432987235

Maybe place this output as close as possible to the start of the diffs so the reader has more context about what "basis/recent/current" mean in the diff output.

2023-03-02 01:17 UTC, jpautler commented on recipes-ni/ni-base-system-image-tests/files/fs_permissions_diff.py
> +    logger.log('###### Full three-way diff: current vs basis, recent vs basis, current vs recent ######')
Could we insert a newline or two above this to create a visible separation?

2023-03-02 15:57 UTC, mike-petersen-ni commented on recipes-ni/ni-base-system-image-tests/files/fs_permissions_diff.py
> +    logger.prefix_logs[0] += f'(basis={basis_hash}, current={current_hash})'
Pushed change: new first line looks like

    INFO: fs_permissions_diff: 23.3.2d10000 against 23.3.1d10000 291d6685ecf0fea7fbd4744ea8509f91

(94 characters)

2023-03-02 20:46 UTC, jpautler approved these changes
Looks good!

2023-03-03 19:18 UTC, amstewart requested changes
Looks good to me.

Could you squash the PR commits back into the main commits prior to merge?

2023-03-03 19:23 UTC, mike-petersen-ni commented
# Patch v2

Squashed to prepare for merge.

2023-03-03 19:26 UTC, amstewart approved these changes

2023-03-03 19:26 UTC, merged

2023-03-03 19:29 UTC, amstewart commented
Cherry-picked to `nilrt/master/hardknott`.