Enable create-spdx when building images.
ni/meta-nilrt pull request #567
Opened 2023-04-18 12:21 UTC by dylan-matthew-turner

Because [we now skip creating SPDX when a package comes from a remote feed](https://github.com/ni/openembedded-core/pull/90), we can enable creating the spdx zst archives when building images.

To enable it, we need to inherit from create-spdx at the top-level bitbake config, and add it to the list of DISTRO_FEATURES.

I verified this produces the expected archive by building `packagefeed-ni-core` followed by `nilrt-base-system-image`

2023-04-18 14:57 UTC, SparkingSpork requested changes

2023-04-18 14:57 UTC, SparkingSpork commented on conf/distro/nilrt.inc
> +INHERIT += " rm_work create-spdx "
Can you add the `create-spdx` tag in a separate `INHERIT +=` line for clarity? This section is labeled as for configuring how the build handles temporary workspaces for each package. We probably want a separate section with comment that adds just the `create-spdx` tag.

2023-04-18 14:59 UTC, amstewart requested changes

2023-04-18 14:59 UTC, amstewart commented on conf/distro/nilrt.inc
> +INHERIT += " rm_work create-spdx "
MINOR: since the spdx artifacts are a nuance of how _we_ (NI) would like to build the distribution, instead of being a fundamental part of NILRT, I think this code should be moved to `nilrt.conf`.

2023-04-18 17:03 UTC, dylan-matthew-turner commented
I moved the changes to nilrt.conf from nilrt.inc (and thus also split the INHERIT), but I left a change in nilrt.inc to convert one tab in a string of spaces to all spaces for the sake of consistency.

2023-04-18 17:09 UTC, SparkingSpork approved these changes

2023-04-20 14:53 UTC, amstewart approved these changes

2023-04-20 14:53 UTC, merged