Report distro info to DB during Kernel Performance tests
ni/meta-nilrt pull request #595
Opened 2023-07-19 05:40 UTC by dylan-matthew-turner

## Need

We want to be able to sort by distro in our test results

## Implementation

During the test, /etc/os-release is read and parsed for VERSION_ID and DISTRO_CODENAME, and those are stored in the results database as tags called "distro_version" and "distro_name."

In the event that the file cannot be read, the file is improperly formatted, or the keys are missing, the resulting values for those tags will be "unknown".

## Testing

TODO/NA?

2023-07-19 14:53 UTC, amstewart requested changes
LGTM; pending a few minor suggestions.

2023-07-19 14:53 UTC, amstewart commented on recipes-kernel/kernel-tests/kernel-performance-tests-files/upload_cyclictest_results.py
> +    stmts = os_release.split('\n')
I think, if you open in `"r"` mode, you'll be given a TextWrapper object, and then you can just read it with `.readlines()` or something and let the standard libs split lines for you. Does that work?

2023-07-19 14:53 UTC, amstewart commented on recipes-kernel/kernel-tests/kernel-performance-tests-files/upload_cyclictest_results.py
> +    variables = dict(pairs)
Isn't the `map()` already basically a `dict()`? It seems like you should be able to skip the intermediate list here.

2023-07-25 01:12 UTC, dylan-matthew-turner commented
I simplified based on your suggestions and have now run the tests and seen them shown up in Grafana.

During that I noticed one other change necessary which was to strip the newlines as they got reported to Grafana, so I added that change as well.

2023-07-25 01:18 UTC, dylan-matthew-turner commented
Oops, and also I just had to remove surrounding quotes from the reported name. `"kirkstone"\n` to `"kirkstone"` to `kirkstone`

2023-07-25 01:23 UTC, dylan-matthew-turner commented
I can rebase and make these all back to one commit if you'd prefer as well.

2023-07-25 15:09 UTC, amstewart commented
Sure.

2023-07-25 16:34 UTC, blueOkiris commented
Done

2023-07-25 16:35 UTC, dylan-matthew-turner commented
Done

2023-07-26 15:38 UTC, amstewart approved these changes

2023-07-26 15:38 UTC, merged