Added libpcap to ni-internal-deps because of AIM arinc664 dependency
ni/meta-nilrt pull request #606
Opened 2023-08-04 08:56 UTC by fmussi

NI is going to resell a 3rd party hardware from [AIM](https://www.aim-online.com/) and libpcap is needed by systems R&D as part of the Veristand Custom Device to support that hardware. To allow offline installation of the driver, libpcap has to be part of the feeds that are part of the [NI LinuxRT Offline installation support](https://www.ni.com/en/support/downloads/software-products/download.ni-linux-real-time-offline-installation-support.html#487410)

## Testing

I haven't had the chance to test it as it's hard to setup (or I don't have the right documentation) a build toolchain on my end.

2023-08-07 18:22 UTC, chaitu236 reviewed
Can you sign your commit (`git commit -s`)?

> I haven't had the chance to test it as it's hard to setup (or I don't have the right documentation) a build toolchain on my end.

There is a pipeline that can be used for developer builds as described [here](https://dev.azure.com/ni/DevCentral/_git/AppCentral.wiki?version=GC80ca128839c528d4a98385356a8d9ff2d6553459&path=/Organizations/Platform-HW-%26-Drivers/Products/RTOS/Tutorials-%26-Manuals/Building-the-Base-System-Image-with-developer-OpenEmbedded-branches.md&-Drivers%2FProducts%2FRTOS%2FTutorials-=&-Manuals%2FBuilding-the-Base-System-Image-with-developer-OpenEmbedded-branches.md=&_a=preview).

Or if you want to build locally and have access to a Linux machine, instructions in https://github.com/ni/nilrt/blob/nilrt/master/kirkstone/README.md.

2023-08-07 18:47 UTC, amstewart requested changes
OE uses commits as the atomic unit of change, so your commit message should contain your justifications and rationale. Also could you reformat the title to conform to the repo style?

eg. `pkggrp-ni-internal-deps: add libpcap for AIM aric664`

Otherwise, the changes look good to me.

2023-08-21 18:54 UTC, fmussi reviewed
I agree with these chanfges.

2023-08-21 19:06 UTC, fmussi commented
@chaitu236 just signed off my latest commit

2023-08-22 19:06 UTC, chaitu236 commented
Update: I'm working with Fabio to update the commit per nilrt expecations.

2023-08-23 17:21 UTC, chaitu236 approved these changes

2023-08-24 19:38 UTC, amstewart approved these changes

2023-08-24 19:39 UTC, merged