Create symlink to legacy status_led location
ni/meta-nilrt pull request #614
Opened 2023-09-05 16:45 UTC by dylan-matthew-turner

LabVIEW RT uses the older /usr/local/natinst/bin location for status_led while it now resides in /usr/bin.

Even if that gets corrected, we'll want to support earlier versions of LVRT, so the best course of action is to create a symlink to the new path at the old path.

We already [do this for niresetip](https://github.com/ni/meta-nilrt/blob/adf0240e44fbd9711895a37b0e093b82d0db9197/recipes-ni/ni-netcfgutil/ni-netcfgutil.bb#L31C16-L31C16) and other executables as well.

The change to status LED occurs in 22.5 and up, so this should be back ported to hardknott as well.

2023-09-05 20:46 UTC, amstewart approved these changes

2023-09-05 20:47 UTC, amstewart commented
>The change to status LED occurs in 22.5 and up, so this should be back ported to hardknott as well.

The only way this fix would get into a customer's hardknott system would be if we went back and purposefully patched the published NILRT feeds for those releases. Is anyone asking that we do that?

2023-09-05 21:03 UTC, chaitu236 commented
Can you add a link to the WI in description and mention what testing was done

2023-09-05 21:03 UTC, chaitu236 requested changes
Can you add a link to the WI in description and mention what testing was done

2023-09-06 15:06 UTC, dylan-matthew-turner commented
Done

2023-09-06 16:18 UTC, merged