Allow fs manifest test to ignore version changes and make debugging easier
ni/meta-nilrt pull request #665
Opened 2024-01-26 20:47 UTC by jeminor

The existing version of this test notifies us of every version change.  Given how much we're changing these days, suppress the version changes since those are reviewed separately in their respective PRs.

While at it, I also added some command-line option similar to the changes that were just made to the dmesg test.  These could be used in future to reset the manifest basis, if we deem that to be useful.

[AB#2507029](https://ni.visualstudio.com/DevCentral/_workitems/edit/2507029)

### Testing

- [X] Tested with a set of failures we have already seen.  Diff shows only non-version differences.

2024-01-26 20:53 UTC, amstewart approved these changes

2024-01-27 00:04 UTC, chaitu236 approved these changes

2024-01-27 05:19 UTC, jpautler requested changes
LGTM. One small thing to fix.

2024-01-27 05:19 UTC, jpautler commented on recipes-ni/ni-base-system-image-tests/files/fs_permissions_diff.py
> +    parser.add_argument('--skip_upload', help='Skip upload of dmesg record to database. Useful when debugging.', action="store_true")
Change "dmesg records" to "filesystem manifest".

2024-01-29 15:04 UTC, jeminor commented on recipes-ni/ni-base-system-image-tests/files/fs_permissions_diff.py
> +    parser.add_argument('--skip_upload', help='Skip upload of dmesg record to database. Useful when debugging.', action="store_true")
Done thx for noticing the copy/pasta :)

2024-01-29 15:37 UTC, jpautler approved these changes

2024-01-29 15:41 UTC, merged