[next] .github: Add pull request template
ni/meta-nilrt pull request #719
Opened 2024-08-19 22:12 UTC by amstewart

Add a Github PR template to help contributors write high-quality PRs correctly the first time.

# Testing

I don't know how to test this. Opening a new PR against my dev branch doesn't prompt with the template. But this is basically just a copy of what we have been using in the [nilrt-snac repo](https://github.com/ni/nilrt-snac/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

2024-08-19 22:34 UTC, chaitu236 requested changes
Can we move this to under [docs directory](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository#:~:text=in%20the%20repository%27s-,docs%20directory,-%2C%20name%20the%20pull)? Or is there a reason we'd want to keep it hidden in `.github` directory?

2024-08-20 14:04 UTC, amstewart commented
> Can we move this to under [docs directory](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository#:~:text=in%20the%20repository%27s-,docs%20directory,-%2C%20name%20the%20pull)? Or is there a reason we'd want to keep it hidden in `.github` directory?

`.github/` was just my preference. I think it makes more clear that the PR template is only relevant to the github build infrastructure. I like the design of putting all github content under .github, all gitlab content under .gitlab, et c.

2024-08-20 14:19 UTC, chaitu236 approved these changes

2024-08-20 14:22 UTC, merged

2024-08-20 14:29 UTC, chaitu236 commented
Cherry-picked to nilrt/master/kirkstone