meta-nilrt: Upgrade recipes to the latest supported versions
ni/meta-nilrt pull request #727
Opened 2024-09-05 09:06 UTC by rajendra-desai-ni

### Summary of Changes

- Update package version of the recipes to the last released version.
- Removed reduntant PV variable to maintain consistancy across .bb files.

### Justification

The meta-nilrt layer contains some original bitbake recipes (like DKMS), which are unique to the NILRT distro. These recipes will only receive upgrades if the RTOS team commits them. We should make a regular pass during major distro revisions, to consider upgrading these recipes to their latest releases.
[AB#2485737](https://dev.azure.com/ni/DevCentral/_workitems/edit/2485737)

### Testing

TODO: Detail what testing has been done to ensure this submission meets requirements.

* [X] I have built the core package feed with this PR in place. (`bitbake packagefeed-ni-core`)

### Procedure

* [X] I certify that the contents of this pull request complies with the [Developer Certificate of Origin](https://github.com/ni/nilrt/blob/HEAD/docs/CONTRIBUTING.md#developer-certificate-of-origin-dco).

2024-09-05 13:43 UTC, rajendra-desai-ni commented
For the 2nd change that I have mentioned in the description,
- Removed redundant PV variable to maintain consistency across .bb files:
   Some recipes had a "PV" variable defined, (though did not depend on any upstream code) but the others didn't have this 
   variable in .bb files. I went ahead and removed this variable (assuming it would anyways default to 1.0) from such recipes. 
   Let me know if this change is needed. Otherwise, I can just revert those changes and update the details accordingly.

2024-09-05 16:01 UTC, amstewart requested changes
Could you break up this PR into individual recipe changes. Upgrade PRs like this are the most likely to need a revert, if they break something. And it is annoying to have to do a partial revert if onlyone recipe is broken.

2024-09-05 16:01 UTC, amstewart commented on recipes-devtools/ptest-utils/ptest-utils.bb
> -PV = "1.4"
When you don't specify a `PV` in a recipe, and the filename does not have a `_$version.bb` suffix, I think it defaults to `1.0`. We especially don't want that in packages like this, that install content from the recipe's directory, because this is our only way to encode that we have actually upgraded the package contents.

2024-09-05 16:01 UTC, amstewart commented on recipes-kernel/dkms/dkms.bb
> +PV = "3.0.13"
Have you done a review of the changes in this package version? DKMS is a security critical utility with sketchy maintenance. We need to be cautious about accepting changes.

2024-09-05 16:22 UTC, rajendra-desai-ni commented on recipes-devtools/ptest-utils/ptest-utils.bb
> -PV = "1.4"
Understood. Also, even I did not like the idea of removing "PV" for default versions as a part of this PR itself. Thought of creating a separate tech debt to address it (if needed). I am working on a new PR where there are few more recipes that needs an update. I am soon going to add reviewers to it after testing it out (or maybe I can force push the changes to this PR itself). That's the reason I had made this PR as draft.

>Could you break up this PR into individual recipe changes. Upgrade PRs like this are the most likely to need a revert, if they break something. And it is annoying to have to do a partial revert if onlyone recipe is broken.

Sure, I can do this.

2024-09-05 16:34 UTC, rajendra-desai-ni commented on recipes-kernel/dkms/dkms.bb
> +PV = "3.0.13"
I just skimmed through the changes that went in from 3.0.10 to 3.0.13 but did not find such critical commits that needs to be verified (or at least that's what I observed) other than this commit ([CI: install xz-utils on Debian](https://github.com/dell/dkms/pull/393)). But it looks like we are still using older package and not the affected package (5.6.0/5.6.1). Hope I understood it correctly?
![image](https://github.com/user-attachments/assets/6bb005d8-841e-412c-bc12-cea69bc0615f)

Also, is there other way than checking the changes manually that would give proper confirmation that we are not depending on critical changes?

2024-09-05 17:03 UTC, amstewart commented on recipes-kernel/dkms/dkms.bb
> +PV = "3.0.13"
>Also, is there other way than checking the changes manually that would give proper confirmation that we are not depending on critical changes?

No. It just comes down to reviewing the upstream changelog and/or PRs.

2024-09-11 08:58 UTC, rajendra-desai-ni commented on recipes-devtools/ptest-utils/ptest-utils.bb
> -PV = "1.4"
Added each individual recipe changes into its own commits.

2024-09-11 09:00 UTC, rajendra-desai-ni commented on recipes-kernel/dkms/dkms.bb
> +PV = "3.0.13"
I will do a re-review of changes went into dkms. Will publish the PR for review and resolve this comment after that.

2024-09-16 11:11 UTC, rajendra-desai-ni commented on recipes-kernel/dkms/dkms.bb
> +PV = "3.0.13"
I went through all the changes in dkms package from 3.0.10 to 3.0.13 (and in-between versions) and did not encounter any unexpected or unacceptable commits. The changes that went in were mostly test related, readme updates, CI work and other improvements. There were some feature additions which seemed to be non-breaking and not-so-major changes. Marking this comment thread as resolved.

2024-09-16 23:01 UTC, chaitu236 commented on recipes-kernel/dkms/dkms.bb
> +PV = "3.0.13"
Did you try installing some NI drivers on a real target and ensuring that their modules build/install/load without issues?

2024-09-17 14:59 UTC, chaitu236 commented on recipes-kernel/dkms/dkms.bb
> +PV = "3.0.13"
@rajendra-desai-ni

2024-09-17 15:02 UTC, amstewart commented on recipes-kernel/dkms/dkms.bb
> +PV = "3.0.13"
I think the existing PR and client testing we have is sufficient to test a DKMS upgrade. Especially for a patch-rev.

2024-09-17 15:02 UTC, amstewart approved these changes

2024-09-17 15:17 UTC, rajendra-desai-ni commented on recipes-kernel/dkms/dkms.bb
> +PV = "3.0.13"
@chaitu236 : I am able to install some NI drivers on cRIO module with new dkms. I am currently setting up my host machine to run some example VIs on the target. I will update here once done.

2024-09-17 17:36 UTC, rajendra-desai-ni commented on recipes-kernel/dkms/dkms.bb
> +PV = "3.0.13"
@chaitu236 : All the NI drivers that I tried installing on the cRIO module installed without any issues. Was able to run some example VIs as well.

2024-09-17 17:51 UTC, chaitu236 approved these changes

2024-09-17 17:51 UTC, merged