ni-firewalld-config: add
ni/meta-nilrt pull request #756
Opened 2024-10-21 21:02 UTC by rtollert

This package contains firewalld service definitions for NI software and the protocols NI software interacts with. Presently this package only contains service definitions, although other firewalld entities (helpers, policies, zones, etc.) might exist in the future. These service definitions are quite provisional at the moment and are subject to change.

NI has not yet decided on where these service definitions should exist long-term. While firewalld appears to have decided to include many third-party service definitions in firewalld itself, we presently reserve the right to refactor these definitions, e.g. into their associated application IPKs. The ni-firewalld-config package should be treated as essentially transient until further notice.

Fixes AB#2902893.

### Testing

Package install works. `firewall-cmd --zone=public --add-service=ni-labview-realtime` works.

* [X] I have built the core package feed with this PR in place. (`bitbake packagefeed-ni-core`)

### Procedure

* [X] I certify that the contents of this pull request complies with the [Developer Certificate of Origin](https://github.com/ni/nilrt/blob/HEAD/docs/CONTRIBUTING.md#developer-certificate-of-origin-dco).

2024-10-22 19:29 UTC, amstewart requested changes
Content looks good.

What do you think about naming the package like `ni-firewalld-compat` to make more clear that it is a compatibility addon, and not our vendor-specific firewalld configuration.

2024-10-22 21:05 UTC, rtollert commented
`-compat` is extremely similar in connotation to `-legacy`, which is very much not what is being intended here. For instance, here is a selection of Debian packages containing `-compat` — most of these are either to ensure compatibility with older versions of software, or polyfills to allow newer APIs in older versions, or for compatibility with third-party (and presumably older) APIs.

```
root@anysquawk:~# apt-cache search --names-only -- -compat
libavahi-compat-libdnssd1 - Avahi Apple Bonjour compatibility library
libdb1-compat - Berkeley database routines [glibc 2.0/2.1 compatibility]
erlang-unicode-util-compat - unicode_util compatibility library for Erlang <= 20
libgdbm-compat4 - GNU dbm database routines (legacy support runtime version)
graphicsmagick-imagemagick-compat - image processing tools providing ImageMagick interface
lua-compat53 - Lua-5.3-style APIs for Lua 5.2 and 5.1
node-winston-compat - Core functionality from winston < 3.0.0
libbigarray-compat-ocaml - compatibility library for Stdlib.Bigarray (runtime)
oss-compat - Open Sound System (OSS) compatibility package
php-random-compat - PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
libecpg-compat3 - older version of run-time library for ECPG programs
libsdl1.2-compat - SDL 1.2 binary compatibility library wrapping SDL 2.0
```

AFAIK, in no instance whatsoever does `-compat` connote providing new functionality by utilizing a third-party API.

I think I might be ok with `ni-firewalld-servicedefs`, i.e. it's what it says on the tin.

2024-10-22 21:08 UTC, amstewart commented
I'm fine with that.

2024-10-23 23:00 UTC, rtollert commented
v2: s/ni-firewalld-config/ni-firewalld-servicedefs/g, and associated message wordsmithing.

2024-10-24 14:55 UTC, amstewart approved these changes

2024-10-24 15:53 UTC, chaitu236 commented
Is this meant for both kirkstone and next branches?

Please note that kirkstone changes aren't getting built in azdo due to https://dev.azure.com/ni/DevCentral/_workitems/edit/2847252 and may not get built for a while due to upcoming dist-next switch.

2024-10-24 16:44 UTC, amstewart commented
Yes; this is meant for kirkstone and scarthgap.

2024-10-24 19:05 UTC, chaitu236 approved these changes

2024-10-24 19:09 UTC, merged

2024-10-24 19:17 UTC, chaitu236 commented
Cherry-picked to nilrt/master/next - a94fc62a58067ae8d13d5e1ff31043b9cb52d71a