nilrt-base-system-image.postinst: Upgrade opkg-keyrings before updating other opkg sources
ni/meta-nilrt pull request #795
Opened 2024-12-30 09:52 UTC by pratheekshasn

### Summary of Changes

The BSI postinst script previously upgraded opkg-keyrings (to get the newly added signing key) after running the command `opkg update`, which in turn verifies the validity of all the feeds accessible by opkg.

This PR changes the order in which these commands are run because:
1. The dist feed (where opkg-keyrings is present) does not require another update, since it is already signed with the previous public key.
2. The validation of the other feeds would fail if they are already signed with the new key, and the target hasn't obtained the new key yet. This can be fixed by obtaining the new key first, i.e., upgrading opkg-keyrings.

### Justification

Although the postinst script does not throw any errors, upgrading the keyring before validating the other opkg sources makes more sense.

### Testing

Tested by building the base system image and installing on a target. Made sure that the opkg-keyrings gets updated before the other opkg sources are fetched and validated.

* [ ] I have built the core package feed with this PR in place. (`bitbake packagefeed-ni-core`)

### Procedure

* [ ] I certify that the contents of this pull request complies with the [Developer Certificate of Origin](https://github.com/ni/nilrt/blob/HEAD/docs/CONTRIBUTING.md#developer-certificate-of-origin-dco).

2024-12-30 10:59 UTC, prasanna-nib approved these changes

2024-12-31 15:59 UTC, chaitu236 requested changes
NAK.

> The dist feed (where opkg-keyrings is present) does not require another update, since it is already signed with the previous public key.


> The validation of the other feeds would fail if they are already signed with the new key, and the target hasn't obtained the new key yet. This can be fixed by obtaining the new key first, i.e., upgrading opkg-keyrings.

I'm not sure this does what you're trying to accomplish.

First, I'm not sure if opkg would allow installation/upgrades of packages if the underlying signing key changed even if we don't run `opkg update` first. Can you provide more information on what and how exactly you tested?

Also, `opkg update` updates target's idea of what the feed actually looks like. If we don't run that before doing `opkg upgrade`, opkg may try to fetch old packages which may no longer be present in the feed. Even if the older package is present in the feed, it will be the old opkg-keyrings version that doesn't have the new key; so I don't see how this is useful.

2025-01-01 05:16 UTC, pratheekshasn commented
Right, that makes sense. But I thought we might need to do this since without the new signing key, running an update results in a failure for all the other feeds which are signed with the new key.

2025-01-06 22:08 UTC, chaitu236 commented
@pratheekshasn Has the BTR tests issue that prompted this PR been addressed? Can we discard this PR?

2025-01-07 07:10 UTC, pratheekshasn commented
> @pratheekshasn Has the BTR tests issue that prompted this PR been addressed? Can we discard this PR?

Yes, they have closed it, I will be closing this PR.

2025-01-07 07:10 UTC, closed without merging